#!/bin/bash

echo "=> Building the image $IMAGE_NAME"
export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
       BUILD_VERSION=$CACHE_TAG \
       VCS_REF=`git rev-parse --short HEAD`

docker pull $IMAGE_NAME || true
docker build --cache-from $IMAGE_NAME \
             --compress \
             --label "org.label-schema.build-date=$BUILD_DATE" \
             --label "org.label-schema.name='The PHP Docker Image'" \
             --label "org.label-schema.description='The PHP Docker Image'" \
             --label "org.label-schema.url='https://github.com/oanhnn/docker-php'" \
             --label "org.label-schema.vcs-url='https://github.com/oanhnn/docker-php.git'" \
             --label "org.label-schema.vcs-ref=$VCS_REF" \
             --label "org.label-schema.version=$BUILD_VERSION" \
             --label "org.label-schema.schema-version=1.0" \
             --pull \
             --tag $IMAGE_NAME .
