#!/bin/bash

echo "=> Building the image"
docker pull $IMAGE_NAME || true
docker build --cache-from $IMAGE_NAME \
             --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg VERSION=$CACHE_TAG \
             -t $IMAGE_NAME $DOCKERFILE_PATH
