name: CI-CD

on:
  push:
    branches:
      - master
      - develop

env:
  DOCKER_IMAGE: oanhnn/php

jobs:
  build:
    name: Build, test and publish image for tag ${{ matrix.php }}-${{ matrix.variant }}
    strategy:
      matrix:
        php:
          - 7.0
          - 7.1
          - 7.2
          - 7.3
          - 7.4
          - 8.0-rc
        variant:
          # - apache
          # - cli
          # - fpm
          # - zts
          - cli-alpine
          - fpm-alpine
          - zts-alpine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: vars
        run: |
          if [[ "${{ matrix.variant }}" =~ ^.*alpine$ ]]; then BASE_OS="alpine"; else BASE_OS="buster"; fi
          # Set step output
          echo "::set-output name=base_os::$(echo $BASE_OS)"
          echo "::set-output name=version::$(echo ${{ matrix.php }}-${{ matrix.variant }})"
          echo "::set-output name=created::$(date --utc --iso-8601=seconds | sed 's/+00.00/Z/g')"

      - name: Build image
        run: |
          cd ${{ matrix.php }}/${{ steps.vars.outputs.base_os }}
          docker build --pull --cache-from $DOCKER_IMAGE:${{ steps.vars.outputs.version }} \
                       --label "org.opencontainers.image.title='The PHP Docker Image'" \
                       --label "org.opencontainers.image.authors=oanhnn" \
                       --label "org.opencontainers.image.licenses=MIT" \
                       --label "org.opencontainers.image.version=${{ matrix.php }}" \
                       --label "org.opencontainers.image.created=${{ steps.vars.outputs.created }}" \
                       --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
                       --label "org.opencontainers.image.revision=${{ github.sha }}" \
                       --build-arg VERSION=${{ steps.vars.outputs.version }} \
                       --tag $DOCKER_IMAGE:test .
      - name: Test php version
        run: |
          docker run --rm $DOCKER_IMAGE:test php -v
          docker run --rm $DOCKER_IMAGE:test php -m

      # - name: Publish image to Docker Hub
      #   if: github.event_name != 'pull_request'
      #   run: |
      #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      #     docker tag $DOCKER_IMAGE:test $DOCKER_IMAGE:${{ steps.vars.outputs.version }}
      #     docker push $DOCKER_IMAGE:${{ steps.vars.outputs.version }}
